AWSTemplateFormatVersion: 2010-09-09

Description: A fully managed streaming application based on Apache Flink, Amazon Kinesis Data Streams, Amazon Kinesis Data Analytics for Java Applications, and Amazon Elasticsearch Service.

Parameters:
  GitHubOAuthToken:
    Description: Optional. Create a token with 'repo' and 'admin:repo_hook' permissions here https://github.com/settings/tokens
    Type: String
    NoEcho: true

  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EC2 instance for replaying events
    ConstraintDescription: MuSt be the name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  ClientIpAddressRange:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Description: IP address range that is able to access the EC2 instance and that gets full read and write access to the Elasticsearch Cluster and the Kibana dashboard
    MaxLength: 18
    MinLength: 9
    Type: String


Outputs:
  KinesisReplayInstance:
    Description: SSH connection to the instance that ingests trip events into the Kinesis stream
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.KinesisReplayInstance

  ProducerCommand:
    Description: Command to populate Kinesis stream with taxi trip events
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.ProducerCommand

  KibanaDashboardURL:
    Description: URL to access the Kibana dasboard
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.KibanaDashboardURL

  CloudWatchDashboardURL:
    Description: URL to access metrics in a CloudWatch dasboard
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.CloudWatchDashboardURL


Resources:
  KinesisReplayBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-bigdata-blog/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/kinesis-replay-build-pipeline.yml
      Parameters:
        ExternalArtifactBucket: !Ref ArtifactBucket
        GitHubOAuthToken: !Ref GitHubOAuthToken
  
  FlinkKinesisConnectorBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-bigdata-blog/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/flink-kinesis-connector-build-pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  TaxiConsumerBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-bigdata-blog/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/kinesis-analytics-taxi-consumer-build-pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        GitHubOAuthToken: !Ref GitHubOAuthToken

  TaxiConsumerInfrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-bigdata-blog/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/kinesis-analytics-taxi-consumer-infrastructure.yml
      Parameters:
        KinesisReplayCopyCommand: !GetAtt KinesisReplayBuildStack.Outputs.KinesisReplayCopyCommand
        FlinkApplicationS3BucketArn: !GetAtt ArtifactBucket.Arn
        FlinkApplicationS3Path: !GetAtt TaxiConsumerBuildStack.Outputs.FlinkApplicationS3Path
        SshKeyName: !Ref SshKeyName
        ClientIpAddressRange: !Ref ClientIpAddressRange

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

